# Generated by Django 6.0.3 on 2026-04-29 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CorporateCalendar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Календарь корпоративных событий', max_length=255, verbose_name='Название')),
                ('period_label', models.CharField(max_length=100, verbose_name='Период')),
                ('file', models.FileField(upload_to='investors/calendar/', verbose_name='Файл')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Корпоративный календарь',
                'verbose_name_plural': 'Корпоративные календари',
            },
        ),
        migrations.CreateModel(
            name='AffiliatedPersonsList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField(verbose_name='Год')),
                ('quarter', models.PositiveSmallIntegerField(choices=[(1, '1 квартал'), (2, '2 квартал'), (3, '3 квартал'), (4, '4 квартал')], verbose_name='Квартал')),
                ('file', models.FileField(upload_to='investors/affiliated/', verbose_name='Файл')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Список аффилированных лиц',
                'verbose_name_plural': 'Списки аффилированных лиц',
                'ordering': ['-year', '-quarter'],
                'unique_together': {('year', 'quarter')},
            },
        ),
        migrations.CreateModel(
            name='FinancialReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField(verbose_name='Год')),
                ('report_type', models.CharField(choices=[('consolidated', 'Консолидированная'), ('separate', 'Отдельная')], max_length=20, verbose_name='Тип')),
                ('file', models.FileField(upload_to='investors/financial/', verbose_name='Файл')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Финансовая отчётность',
                'verbose_name_plural': 'Финансовая отчётность',
                'ordering': ['-year', 'report_type'],
                'unique_together': {('year', 'report_type')},
            },
        ),
    ]
