# Generated by Django 6.0.3 on 2026-04-29 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CorporateEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('month', models.PositiveSmallIntegerField(choices=[(1, 'Январь'), (2, 'Февраль'), (3, 'Март'), (4, 'Апрель'), (5, 'Май'), (6, 'Июнь'), (7, 'Июль'), (8, 'Август'), (9, 'Сентябрь'), (10, 'Октябрь'), (11, 'Ноябрь'), (12, 'Декабрь')], verbose_name='Месяц')),
                ('year', models.PositiveIntegerField(verbose_name='Год')),
            ],
            options={
                'verbose_name': 'Корпоративное событие',
                'verbose_name_plural': 'Корпоративные события',
                'ordering': ['year', 'month'],
            },
        ),
        migrations.DeleteModel(
            name='CorporateCalendar',
        ),
    ]
