# Generated by Django 6.0.3 on 2026-05-13 07:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_corporateevent_delete_corporatecalendar'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrgUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('count', models.CharField(blank=True, max_length=20, verbose_name='Кол-во единиц')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Порядок')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='core.orgunit', verbose_name='Родительский узел')),
            ],
            options={
                'verbose_name': 'Подразделение',
                'verbose_name_plural': 'Организационная структура',
                'ordering': ['order', 'id'],
            },
        ),
    ]
