# Generated by Django 6.0.3 on 2026-05-13 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_orgunit'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrgChart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='org/', verbose_name='Схема структуры')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Организационная структура',
                'verbose_name_plural': 'Организационная структура',
            },
        ),
    ]
