# Generated by Django 6.0.3 on 2026-06-25 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_privacy_policy'),
    ]

    operations = [
        migrations.AddField(
            model_name='corporateevent',
            name='title_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='corporateevent',
            name='title_kk',
            field=models.CharField(max_length=255, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='corporateevent',
            name='title_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='orgunit',
            name='name_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='orgunit',
            name='name_kk',
            field=models.CharField(max_length=255, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='orgunit',
            name='name_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='privacypolicy',
            name='document_title_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Название документа'),
        ),
        migrations.AddField(
            model_name='privacypolicy',
            name='document_title_kk',
            field=models.CharField(max_length=255, null=True, verbose_name='Название документа'),
        ),
        migrations.AddField(
            model_name='privacypolicy',
            name='document_title_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Название документа'),
        ),
        migrations.AddField(
            model_name='privacypolicy',
            name='hero_label_en',
            field=models.CharField(default='АО «Казгеология»', max_length=100, null=True, verbose_name='Метка в шапке'),
        ),
        migrations.AddField(
            model_name='privacypolicy',
            name='hero_label_kk',
            field=models.CharField(default='АО «Казгеология»', max_length=100, null=True, verbose_name='Метка в шапке'),
        ),
        migrations.AddField(
            model_name='privacypolicy',
            name='hero_label_ru',
            field=models.CharField(default='АО «Казгеология»', max_length=100, null=True, verbose_name='Метка в шапке'),
        ),
        migrations.AddField(
            model_name='privacypolicy',
            name='hero_subtitle_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Подзаголовок страницы'),
        ),
        migrations.AddField(
            model_name='privacypolicy',
            name='hero_subtitle_kk',
            field=models.CharField(max_length=255, null=True, verbose_name='Подзаголовок страницы'),
        ),
        migrations.AddField(
            model_name='privacypolicy',
            name='hero_subtitle_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Подзаголовок страницы'),
        ),
        migrations.AddField(
            model_name='privacypolicy',
            name='hero_title_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Заголовок страницы'),
        ),
        migrations.AddField(
            model_name='privacypolicy',
            name='hero_title_kk',
            field=models.CharField(max_length=255, null=True, verbose_name='Заголовок страницы'),
        ),
        migrations.AddField(
            model_name='privacypolicy',
            name='hero_title_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Заголовок страницы'),
        ),
        migrations.AddField(
            model_name='privacypolicy',
            name='intro_text_en',
            field=models.TextField(null=True, verbose_name='Вводный текст'),
        ),
        migrations.AddField(
            model_name='privacypolicy',
            name='intro_text_kk',
            field=models.TextField(null=True, verbose_name='Вводный текст'),
        ),
        migrations.AddField(
            model_name='privacypolicy',
            name='intro_text_ru',
            field=models.TextField(null=True, verbose_name='Вводный текст'),
        ),
        migrations.AddField(
            model_name='privacypolicy',
            name='updated_date_en',
            field=models.CharField(max_length=100, null=True, verbose_name='Дата обновления'),
        ),
        migrations.AddField(
            model_name='privacypolicy',
            name='updated_date_kk',
            field=models.CharField(max_length=100, null=True, verbose_name='Дата обновления'),
        ),
        migrations.AddField(
            model_name='privacypolicy',
            name='updated_date_ru',
            field=models.CharField(max_length=100, null=True, verbose_name='Дата обновления'),
        ),
        migrations.AddField(
            model_name='privacypolicysection',
            name='content_en',
            field=models.TextField(help_text='Для нескольких абзацев разделяйте текст пустой строкой.', null=True, verbose_name='Текст секции'),
        ),
        migrations.AddField(
            model_name='privacypolicysection',
            name='content_kk',
            field=models.TextField(help_text='Для нескольких абзацев разделяйте текст пустой строкой.', null=True, verbose_name='Текст секции'),
        ),
        migrations.AddField(
            model_name='privacypolicysection',
            name='content_ru',
            field=models.TextField(help_text='Для нескольких абзацев разделяйте текст пустой строкой.', null=True, verbose_name='Текст секции'),
        ),
        migrations.AddField(
            model_name='privacypolicysection',
            name='list_items_en',
            field=models.TextField(blank=True, help_text='Каждый пункт с новой строки.', null=True, verbose_name='Пункты списка'),
        ),
        migrations.AddField(
            model_name='privacypolicysection',
            name='list_items_kk',
            field=models.TextField(blank=True, help_text='Каждый пункт с новой строки.', null=True, verbose_name='Пункты списка'),
        ),
        migrations.AddField(
            model_name='privacypolicysection',
            name='list_items_ru',
            field=models.TextField(blank=True, help_text='Каждый пункт с новой строки.', null=True, verbose_name='Пункты списка'),
        ),
        migrations.AddField(
            model_name='privacypolicysection',
            name='title_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Заголовок секции'),
        ),
        migrations.AddField(
            model_name='privacypolicysection',
            name='title_kk',
            field=models.CharField(max_length=255, null=True, verbose_name='Заголовок секции'),
        ),
        migrations.AddField(
            model_name='privacypolicysection',
            name='title_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Заголовок секции'),
        ),
    ]
