# Generated by Django 6.0.3 on 2026-06-25 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0003_board_committees'),
    ]

    operations = [
        migrations.AddField(
            model_name='boardcommittee',
            name='count_label_en',
            field=models.CharField(max_length=50, null=True, verbose_name='Подпись количества'),
        ),
        migrations.AddField(
            model_name='boardcommittee',
            name='count_label_kk',
            field=models.CharField(max_length=50, null=True, verbose_name='Подпись количества'),
        ),
        migrations.AddField(
            model_name='boardcommittee',
            name='count_label_ru',
            field=models.CharField(max_length=50, null=True, verbose_name='Подпись количества'),
        ),
        migrations.AddField(
            model_name='boardcommittee',
            name='title_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Название комитета'),
        ),
        migrations.AddField(
            model_name='boardcommittee',
            name='title_kk',
            field=models.CharField(max_length=255, null=True, verbose_name='Название комитета'),
        ),
        migrations.AddField(
            model_name='boardcommittee',
            name='title_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Название комитета'),
        ),
        migrations.AddField(
            model_name='boardcommitteemember',
            name='full_name_en',
            field=models.CharField(max_length=255, null=True, verbose_name='ФИО'),
        ),
        migrations.AddField(
            model_name='boardcommitteemember',
            name='full_name_kk',
            field=models.CharField(max_length=255, null=True, verbose_name='ФИО'),
        ),
        migrations.AddField(
            model_name='boardcommitteemember',
            name='full_name_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='ФИО'),
        ),
        migrations.AddField(
            model_name='boardcommitteemember',
            name='note_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Примечание'),
        ),
        migrations.AddField(
            model_name='boardcommitteemember',
            name='note_kk',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Примечание'),
        ),
        migrations.AddField(
            model_name='boardcommitteemember',
            name='note_ru',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Примечание'),
        ),
        migrations.AddField(
            model_name='boardcommitteemember',
            name='role_label_en',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Метка роли'),
        ),
        migrations.AddField(
            model_name='boardcommitteemember',
            name='role_label_kk',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Метка роли'),
        ),
        migrations.AddField(
            model_name='boardcommitteemember',
            name='role_label_ru',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Метка роли'),
        ),
        migrations.AddField(
            model_name='boardmember',
            name='full_name_en',
            field=models.CharField(max_length=255, null=True, verbose_name='ФИО'),
        ),
        migrations.AddField(
            model_name='boardmember',
            name='full_name_kk',
            field=models.CharField(max_length=255, null=True, verbose_name='ФИО'),
        ),
        migrations.AddField(
            model_name='boardmember',
            name='full_name_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='ФИО'),
        ),
        migrations.AddField(
            model_name='boardmember',
            name='role_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Роль'),
        ),
        migrations.AddField(
            model_name='boardmember',
            name='role_kk',
            field=models.CharField(max_length=255, null=True, verbose_name='Роль'),
        ),
        migrations.AddField(
            model_name='boardmember',
            name='role_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Роль'),
        ),
        migrations.AddField(
            model_name='boardsecretary',
            name='full_name_en',
            field=models.CharField(max_length=255, null=True, verbose_name='ФИО'),
        ),
        migrations.AddField(
            model_name='boardsecretary',
            name='full_name_kk',
            field=models.CharField(max_length=255, null=True, verbose_name='ФИО'),
        ),
        migrations.AddField(
            model_name='boardsecretary',
            name='full_name_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='ФИО'),
        ),
        migrations.AddField(
            model_name='boardsecretary',
            name='label_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Должность'),
        ),
        migrations.AddField(
            model_name='boardsecretary',
            name='label_kk',
            field=models.CharField(max_length=255, null=True, verbose_name='Должность'),
        ),
        migrations.AddField(
            model_name='boardsecretary',
            name='label_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Должность'),
        ),
    ]
