# Generated by Django 6.0.3 on 2026-05-22 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='О КОМПАНИИ', max_length=100, verbose_name='Заголовок секции')),
                ('description', models.TextField(verbose_name='Текст описания (абзац)')),
                ('main_stat_description', models.CharField(max_length=255, verbose_name='Описание главного показателя')),
                ('main_stat_value', models.CharField(max_length=50, verbose_name='Значение главного показателя')),
                ('main_stat_has_plus', models.BooleanField(default=True, verbose_name='Показывать плюс (+)')),
            ],
            options={
                'verbose_name': "Секция 'О компании'",
                'verbose_name_plural': "Секция 'О компании'",
            },
        ),
        migrations.CreateModel(
            name='AboutStatistic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255, verbose_name='Описание показателя')),
                ('value', models.CharField(max_length=50, verbose_name='Значение')),
                ('label', models.CharField(max_length=100, verbose_name='Подпись показателя (например: СПЕЦИАЛИСТОВ)')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок отображения')),
            ],
            options={
                'verbose_name': 'Дополнительный показатель',
                'verbose_name_plural': 'Дополнительные показатели',
                'ordering': ['order', 'id'],
            },
        ),
    ]
