# Generated by Django 6.0.3 on 2026-06-25 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0003_about_history_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='abouthistoryevent',
            name='date_label_en',
            field=models.CharField(max_length=100, null=True, verbose_name='Дата'),
        ),
        migrations.AddField(
            model_name='abouthistoryevent',
            name='date_label_kk',
            field=models.CharField(max_length=100, null=True, verbose_name='Дата'),
        ),
        migrations.AddField(
            model_name='abouthistoryevent',
            name='date_label_ru',
            field=models.CharField(max_length=100, null=True, verbose_name='Дата'),
        ),
        migrations.AddField(
            model_name='abouthistoryevent',
            name='description_en',
            field=models.TextField(null=True, verbose_name='Описание события'),
        ),
        migrations.AddField(
            model_name='abouthistoryevent',
            name='description_kk',
            field=models.TextField(null=True, verbose_name='Описание события'),
        ),
        migrations.AddField(
            model_name='abouthistoryevent',
            name='description_ru',
            field=models.TextField(null=True, verbose_name='Описание события'),
        ),
        migrations.AddField(
            model_name='abouthistoryevent',
            name='title_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Заголовок события'),
        ),
        migrations.AddField(
            model_name='abouthistoryevent',
            name='title_kk',
            field=models.CharField(max_length=255, null=True, verbose_name='Заголовок события'),
        ),
        migrations.AddField(
            model_name='abouthistoryevent',
            name='title_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Заголовок события'),
        ),
        migrations.AddField(
            model_name='aboutsection',
            name='description_en',
            field=models.TextField(null=True, verbose_name='Текст описания (абзац)'),
        ),
        migrations.AddField(
            model_name='aboutsection',
            name='description_kk',
            field=models.TextField(null=True, verbose_name='Текст описания (абзац)'),
        ),
        migrations.AddField(
            model_name='aboutsection',
            name='description_ru',
            field=models.TextField(null=True, verbose_name='Текст описания (абзац)'),
        ),
        migrations.AddField(
            model_name='aboutsection',
            name='main_stat_description_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Описание главного показателя'),
        ),
        migrations.AddField(
            model_name='aboutsection',
            name='main_stat_description_kk',
            field=models.CharField(max_length=255, null=True, verbose_name='Описание главного показателя'),
        ),
        migrations.AddField(
            model_name='aboutsection',
            name='main_stat_description_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Описание главного показателя'),
        ),
        migrations.AddField(
            model_name='aboutsection',
            name='main_stat_value_en',
            field=models.CharField(max_length=50, null=True, verbose_name='Значение главного показателя'),
        ),
        migrations.AddField(
            model_name='aboutsection',
            name='main_stat_value_kk',
            field=models.CharField(max_length=50, null=True, verbose_name='Значение главного показателя'),
        ),
        migrations.AddField(
            model_name='aboutsection',
            name='main_stat_value_ru',
            field=models.CharField(max_length=50, null=True, verbose_name='Значение главного показателя'),
        ),
        migrations.AddField(
            model_name='aboutsection',
            name='title_en',
            field=models.CharField(default='О КОМПАНИИ', max_length=100, null=True, verbose_name='Заголовок секции'),
        ),
        migrations.AddField(
            model_name='aboutsection',
            name='title_kk',
            field=models.CharField(default='О КОМПАНИИ', max_length=100, null=True, verbose_name='Заголовок секции'),
        ),
        migrations.AddField(
            model_name='aboutsection',
            name='title_ru',
            field=models.CharField(default='О КОМПАНИИ', max_length=100, null=True, verbose_name='Заголовок секции'),
        ),
        migrations.AddField(
            model_name='aboutstatistic',
            name='description_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Описание показателя'),
        ),
        migrations.AddField(
            model_name='aboutstatistic',
            name='description_kk',
            field=models.CharField(max_length=255, null=True, verbose_name='Описание показателя'),
        ),
        migrations.AddField(
            model_name='aboutstatistic',
            name='description_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Описание показателя'),
        ),
        migrations.AddField(
            model_name='aboutstatistic',
            name='label_en',
            field=models.CharField(max_length=100, null=True, verbose_name='Подпись показателя (например: СПЕЦИАЛИСТОВ)'),
        ),
        migrations.AddField(
            model_name='aboutstatistic',
            name='label_kk',
            field=models.CharField(max_length=100, null=True, verbose_name='Подпись показателя (например: СПЕЦИАЛИСТОВ)'),
        ),
        migrations.AddField(
            model_name='aboutstatistic',
            name='label_ru',
            field=models.CharField(max_length=100, null=True, verbose_name='Подпись показателя (например: СПЕЦИАЛИСТОВ)'),
        ),
        migrations.AddField(
            model_name='aboutstatistic',
            name='value_en',
            field=models.CharField(max_length=50, null=True, verbose_name='Значение'),
        ),
        migrations.AddField(
            model_name='aboutstatistic',
            name='value_kk',
            field=models.CharField(max_length=50, null=True, verbose_name='Значение'),
        ),
        migrations.AddField(
            model_name='aboutstatistic',
            name='value_ru',
            field=models.CharField(max_length=50, null=True, verbose_name='Значение'),
        ),
    ]
